In [178]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [179]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [180]:
train.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
test.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [181]:
train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [182]:
train.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [183]:
train['Age'].fillna(train['Age'].mean(), inplace=True)
test['Age'].fillna(train['Age'].mean(), inplace=True)
test['Fare'].fillna(train['Fare'].mean(), inplace=True)

In [184]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(train['Pclass'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([1, 2, 3], dtype=int64)

In [185]:
train.drop(['Pclass'], axis=1, inplace=True)
train['Class1'] = hot_encoded[:,0]
train['Class2'] = hot_encoded[:,1]
train['Class3'] = hot_encoded[:,2]

In [186]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(test['Pclass'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([1, 2, 3], dtype=int64)

In [187]:
test.drop(['Pclass'], axis=1, inplace=True)
test['Class1'] = hot_encoded[:,0]
test['Class2'] = hot_encoded[:,1]
test['Class3'] = hot_encoded[:,2]

In [188]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(train['Sex'])
train['Sex'] = label_encoded

In [189]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(test['Sex'])
test['Sex'] = label_encoded

In [190]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(train['SibSp'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([0, 1, 2, 3, 4, 5, 8], dtype=int64)

In [191]:
train.drop(['SibSp'], axis=1, inplace=True)
train['Sib0'] = hot_encoded[:,0]
train['Sib1'] = hot_encoded[:,1]
train['Sib2'] = hot_encoded[:,2]
train['Sib3'] = hot_encoded[:,3]
train['Sib4'] = hot_encoded[:,4]
train['Sib5'] = hot_encoded[:,5]
train['Sib8'] = hot_encoded[:,6]

In [192]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(test['SibSp'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([0, 1, 2, 3, 4, 5, 8], dtype=int64)

In [193]:
test.drop(['SibSp'], axis=1, inplace=True)
test['Sib0'] = hot_encoded[:,0]
test['Sib1'] = hot_encoded[:,1]
test['Sib2'] = hot_encoded[:,2]
test['Sib3'] = hot_encoded[:,3]
test['Sib4'] = hot_encoded[:,4]
test['Sib5'] = hot_encoded[:,5]
test['Sib8'] = hot_encoded[:,6]

In [194]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(train['Parch'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [195]:
train.drop(['Parch'], axis=1, inplace=True)
train['Parch0'] = hot_encoded[:,0]
train['Parch1'] = hot_encoded[:,1]
train['Parch2'] = hot_encoded[:,2]
train['Parch3'] = hot_encoded[:,3]
train['Parch4'] = hot_encoded[:,4]
train['Parch5'] = hot_encoded[:,5]
train['Parch6'] = hot_encoded[:,6]

In [196]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(test['Parch'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array([0, 1, 2, 3, 4, 5, 6, 9], dtype=int64)

In [197]:
test.drop(['Parch'], axis=1, inplace=True)
test['Parch0'] = hot_encoded[:,0]
test['Parch1'] = hot_encoded[:,1]
test['Parch2'] = hot_encoded[:,2]
test['Parch3'] = hot_encoded[:,3]
test['Parch4'] = hot_encoded[:,4]
test['Parch5'] = hot_encoded[:,5]
test['Parch6'] = hot_encoded[:,6]
test['Parch9'] = hot_encoded[:,7]

In [198]:
train['Embarked'].fillna('Unknown', inplace=True)
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(train['Embarked'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array(['C', 'Q', 'S', 'Unknown'], dtype=object)

In [199]:
train.drop(['Embarked'], axis=1, inplace=True)
train['EmbarkedC'] = hot_encoded[:,0]
train['EmbarkedQ'] = hot_encoded[:,1]
train['EmbarkedS'] = hot_encoded[:,2]
train['EmbarkedUnknown'] = hot_encoded[:,3]

In [200]:
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(test['Embarked'])
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array(['C', 'Q', 'S'], dtype=object)

In [201]:
test.drop(['Embarked'], axis=1, inplace=True)
test['EmbarkedC'] = hot_encoded[:,0]
test['EmbarkedQ'] = hot_encoded[:,1]
test['EmbarkedS'] = hot_encoded[:,2]

In [202]:
train['Cabin'].fillna('Unknown', inplace=True)
cabin = []
for i in range(len(train)):
    cabin.append(train['Cabin'][i][:1])
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(cabin)
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', 'U'],
      dtype='<U1')

In [203]:
train.drop(['Cabin'], axis=1, inplace=True)
train['CabinA'] = hot_encoded[:,0]
train['CabinB'] = hot_encoded[:,1]
train['CabinC'] = hot_encoded[:,2]
train['CabinD'] = hot_encoded[:,3]
train['CabinE'] = hot_encoded[:,4]
train['CabinF'] = hot_encoded[:,5]
train['CabinG'] = hot_encoded[:,6]
train['CabinT'] = hot_encoded[:,7]

In [204]:
test['Cabin'].fillna('Unknown', inplace=True)
cabin = []
for i in range(len(test)):
    cabin.append(test['Cabin'][i][:1])
enc_label = LabelEncoder()
label_encoded = enc_label.fit_transform(cabin)
enc_onehot = OneHotEncoder(sparse=False)
hot_encoded = enc_onehot.fit_transform(label_encoded.reshape(-1, 1))
enc_label.classes_

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'U'],
      dtype='<U1')

In [214]:
import numpy as np
test.drop(['Cabin'], axis=1, inplace=True)
test['CabinA'] = hot_encoded[:,0]
test['CabinB'] = hot_encoded[:,1]
test['CabinC'] = hot_encoded[:,2]
test['CabinD'] = hot_encoded[:,3]
test['CabinE'] = hot_encoded[:,4]
test['CabinF'] = hot_encoded[:,5]
test['CabinG'] = hot_encoded[:,6]
test['CabinT'] = np.zeros(len(test))

ValueError: labels ['Cabin'] not contained in axis

In [206]:
train.head()

Survived  Sex   Age     Fare  Class1  Class2  Class3  Sib0  Sib1  Sib2  \
0         0    1  22.0   7.2500     0.0     0.0     1.0   0.0   1.0   0.0   
1         1    0  38.0  71.2833     1.0     0.0     0.0   0.0   1.0   0.0   
2         1    0  26.0   7.9250     0.0     0.0     1.0   1.0   0.0   0.0   
3         1    0  35.0  53.1000     1.0     0.0     0.0   0.0   1.0   0.0   
4         0    1  35.0   8.0500     0.0     0.0     1.0   1.0   0.0   0.0   

    ...    EmbarkedS  EmbarkedUnknown  CabinA  CabinB  CabinC  CabinD  CabinE  \
0   ...          1.0              0.0     0.0     0.0     0.0     0.0     0.0   
1   ...          0.0              0.0     0.0     0.0     1.0     0.0     0.0   
2   ...          1.0              0.0     0.0     0.0     0.0     0.0     0.0   
3   ...          1.0              0.0     0.0     0.0     1.0     0.0     0.0   
4   ...          1.0              0.0     0.0     0.0     0.0     0.0     0.0   

   CabinF  CabinG  CabinT  
0     0.0     0.0     0.0  
1     0.0     0.0     0.0  
2     0.0     0.0     0.0  
3     0.0     0.0     0.0  
4     0.0     0.0     0.0  

[5 rows x 33 columns]

In [207]:
from sklearn.model_selection import train_test_split

x_train = train.drop(['Survived'], axis=1)
y_train = train['Survived']

x_train_train, x_valid, y_train_train, y_valid = train_test_split(x_train, y_train, test_size=0.33, random_state=42) 

In [208]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 

clf = LogisticRegression()
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

0.81355932203389836

In [209]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_lr.csv', index=False)

ValueError: X has 31 features per sample; expecting 32

In [210]:
from sklearn.svm import SVC
clf = SVC(kernel='linear', random_state=42)
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

0.80000000000000004

In [211]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_svm.csv', index=False)

ValueError: X.shape[1] = 31 should be equal to 32, the number of features at training time

In [ ]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(max_iter=1000, random_state=42)
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

In [ ]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_SGD.csv', index=False)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=25, weights='distance')
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

In [ ]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_KNN.csv', index=False)

In [ ]:
from sklearn.gaussian_process import GaussianProcessClassifier
clf = GaussianProcessClassifier()
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

In [ ]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_GP.csv', index=False)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy', random_state=42, splitter='random')
clf.fit(x_train_train, y_train_train)
valid_pred = clf.predict(x_valid)
accuracy_score(y_valid, valid_pred)

In [ ]:
clf.fit(x_train, y_train)
test_pred = clf.predict(test)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = test_pred
submission.to_csv('submission_DT.csv', index=False)